### PR TITLE
IPV6 support

### PR DESCRIPTION
**Pull request by lubronzhan**
* Add IPV6 ipam function
* Refactor ipam logic using library go4.org/netipx. Previously the logic to check each ip in the range is not suitable for ipv6 address since there are so many.
* Now of ipv4 address, only skip `.0` and `.255`. Doesn't skip ipv6 address
* More unit test

### CODE REVIEW

**Comment by thebsdbox** [comment]
You beat me to it! I finally started on this, just this week 😂

**Comment by thebsdbox** [comment]
This is excellent !

**Comment by lubronzhan** [comment]
Hopefully you haven't done much work 😂

**Comment by thebsdbox** [comment]
`/lgtm`

**Pull request merged**
